#!/bin/bash -e
#Credits to Hammockt for original bash code


#Creates a temp directory called myTemp
#Copies code into myTemp
old_directory=`pwd`
mkdir myTemp
cp $1/. myTemp -R

#Creates a build of the dominion
#pulls out the output code
cd myTemp
make testdominion
./testdominion $3 > first.out
mv first.out $old_directory
#cd $old_directory

#Clean 
#Copy and make again with the second implementation
rm -f *
cp $2/. . -R
cp $4/. . -R
make testdominion
timeout 10s ./testdominion $3 > second.out
if [ $? != 0 ]; then
	echo "Could not finish tests. Encountered an infinite loop" >> second.out
fi
mv second.out $old_directory
cd $old_directory

#Runs a diff that checks for the results line  
#... reports as such
diff -s -y first.out second.out > diff.out
results=`tail -n 1 < diff.out`
if [ "$results" == "Files first.out and second.out are identical" ]; then
	echo "TEST PASSED"
else
	echo "TEST FAILED"
	echo "first vs second output (left vs right)"
	echo
	cat diff.out
fi

#Clean up
rm -rf myTemp